on:
  push:
    branches:
      - devbi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.CA_CRT }}" > ca.crt
          echo "${{ secrets.USER_CRT }}" > RT_GEN.crt
          echo "${{ secrets.USER_KEY }}" > RT_GEN.key
          echo "${{ secrets.TA_KEY }}" > ta.key

      - name: List files
        run: ls -al .github/vpn

      - name: Connect VPN
        run: sudo openvpn --config ".github/vpn/config.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 10.12.33.149; do sleep 2; done

      - name: Deploy
        run: echo "Connecté à BiBoard dev"

      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn

      # - name: Upload VPN logs
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: VPN logs
      #     path: vpn.log
